# Generated by Django 5.0.3 on 2024-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('sabor', models.TextField(blank=True, max_length=5000)),
                ('color', models.TextField(blank=True, max_length=5000)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
