# Generated by Django 5.0.3 on 2024-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_silla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=5000)),
                ('apellido', models.FloatField(blank=True, max_length=5000)),
                ('cedula', models.IntegerField(max_length=5000)),
                ('telefono', models.IntegerField()),
                ('correo', models.IntegerField(blank=True, max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Silla',
        ),
    ]
