# Generated by Django 5.0.3 on 2024-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_delete_post_delete_silla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
