# Generated by Django 5.0.3 on 2024-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cliente_apellido_alter_cliente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.TextField(blank=True, max_length=5000)),
                ('cedula_cliente', models.IntegerField(max_length=5000)),
                ('descripcion', models.TextField(blank=True, max_length=5000)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
