# Generated by Django 5.0.3 on 2024-05-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.FloatField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.FloatField(blank=True, max_length=5000),
        ),
    ]
