# Generated by Django 5.0.3 on 2024-05-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cliente_cedula_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='cedula_cliente',
            new_name='cedula',
        ),
    ]
